# Generated by Django 3.2.23 on 2025-08-04 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tabelas', '0001_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referencia',
            name='tipofonte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_referencia_tipofonterefer', to='tabelas.tipofonterefer'),
        ),
        migrations.AddField(
            model_name='processoscomite',
            name='comite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_processoscomite_comite', to='processos.comite'),
        ),
        migrations.AddField(
            model_name='processoscomite',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processoscomite',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_processoscomite_processo', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_processo_banco', to='tabelas.banco'),
        ),
        migrations.AddField(
            model_name='processo',
            name='clientepf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_processo_pessoafisica', to='processos.pessoafisica'),
        ),
        migrations.AddField(
            model_name='processo',
            name='clientepj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_processo_pessoajuridica1', to='processos.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='processo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_processo_pessoajuridica', to='processos.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='processo',
            name='finalidadecredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='fk_processo_finalidadecredito', to='tabelas.finalidadecredito'),
        ),
        migrations.AddField(
            model_name='processo',
            name='linhacredito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_processo_linhacredito', to='tabelas.linhacredito'),
        ),
        migrations.AddField(
            model_name='processo',
            name='localizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_processo_localizacao', to='tabelas.localizacao'),
        ),
        migrations.AddField(
            model_name='processo',
            name='veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_processo_veiculo', to='tabelas.veiculo'),
        ),
        migrations.AddField(
            model_name='pjuridicasocio',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pjuridicasocio',
            name='pessoajuridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_pjuridicasocio_pjuridica', to='processos.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='pjuridicasocio',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pjuridicasocio_socio', to='processos.pessoafisica'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_pessoajuridica_bairro', to='tabelas.bairro'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoajuridica_cidade', to='tabelas.cidade'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='ramoatividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoajuridica_ramoatividade', to='tabelas.ramoatividade'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='setornegocio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoajuridica_setornegocio', to='tabelas.setornegocio'),
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoajuridica_situacaopessoa', to='tabelas.situacaopessoa'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_pessoafisica_bairro', to='tabelas.bairro'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoafisica_cidade', to='tabelas.cidade'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='estadocivil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoafisica_estadocivil', to='tabelas.estadocivil'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='naturalidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoafisica_naturalidade', to='tabelas.cidade'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='profissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoafisica_profissao', to='tabelas.profissao'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='regimebens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoafisica_regimebens', to='tabelas.regimebens'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pessoafisica_situacaopessoa', to='tabelas.situacaopessoa'),
        ),
        migrations.AddField(
            model_name='parecer',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parecer',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_parecer_processo', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='negociacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='negociacao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_negociacao_processo', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_movimentacao_destino', to='tabelas.localizacao'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_movimentacao_origem', to='tabelas.localizacao'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_movimentacao_processo', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='membroscomite',
            name='comite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_membroscomite_comite', to='processos.comite'),
        ),
        migrations.AddField(
            model_name='membroscomite',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membroscomite',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_membroscomite_operador', to='tabelas.operador'),
        ),
        migrations.AddField(
            model_name='historicalreferencia',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreferencia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalreferencia',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='historicalreferencia',
            name='tipofonte',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.tipofonterefer'),
        ),
        migrations.AddField(
            model_name='historicalprocessoscomite',
            name='comite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.comite'),
        ),
        migrations.AddField(
            model_name='historicalprocessoscomite',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprocessoscomite',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprocessoscomite',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='banco',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.banco'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='clientepf',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.pessoafisica'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='clientepj',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='finalidadecredito',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.finalidadecredito'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='linhacredito',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.linhacredito'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='localizacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.localizacao'),
        ),
        migrations.AddField(
            model_name='historicalprocesso',
            name='veiculo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.veiculo'),
        ),
        migrations.AddField(
            model_name='historicalpjuridicasocio',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpjuridicasocio',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpjuridicasocio',
            name='pessoajuridica',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.pessoajuridica'),
        ),
        migrations.AddField(
            model_name='historicalpjuridicasocio',
            name='socio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.pessoafisica'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='bairro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.bairro'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='cidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.cidade'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='ramoatividade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.ramoatividade'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='setornegocio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.setornegocio'),
        ),
        migrations.AddField(
            model_name='historicalpessoajuridica',
            name='situacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.situacaopessoa'),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='bairro',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.bairro'),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='cidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.cidade'),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='estadocivil',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.estadocivil'),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='naturalidade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.cidade'),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='profissao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.profissao'),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='regimebens',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.regimebens'),
        ),
        migrations.AddField(
            model_name='historicalpessoafisica',
            name='situacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.situacaopessoa'),
        ),
        migrations.AddField(
            model_name='historicalparecer',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalparecer',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalparecer',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='historicalnegociacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnegociacao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalnegociacao',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='destino',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.localizacao'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='origem',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.localizacao'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacao',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='historicalmembroscomite',
            name='comite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.comite'),
        ),
        migrations.AddField(
            model_name='historicalmembroscomite',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembroscomite',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembroscomite',
            name='operador',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.operador'),
        ),
        migrations.AddField(
            model_name='historicalfinanceiro',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinanceiro',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinanceiro',
            name='negociacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.negociacao'),
        ),
        migrations.AddField(
            model_name='historicalfinanceiro',
            name='parecer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.parecer'),
        ),
        migrations.AddField(
            model_name='historicalfinanceiro',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='historicalcomite',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcomite',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalavalista',
            name='avalista',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.pessoafisica'),
        ),
        migrations.AddField(
            model_name='historicalavalista',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalavalista',
            name='graurelacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tabelas.graurelacao'),
        ),
        migrations.AddField(
            model_name='historicalavalista',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalavalista',
            name='negociacao',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.negociacao'),
        ),
        migrations.AddField(
            model_name='historicalavalista',
            name='processo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='negociacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_financeiro_negociacao', to='processos.negociacao'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='parecer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_financeiro_parecer', to='processos.parecer'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_financeiro_processo', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='comite',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avalista',
            name='avalista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_avalista_pessoafisica', to='processos.pessoafisica'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avalista',
            name='graurelacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_avalista_graurelacao', to='tabelas.graurelacao'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='negociacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.negociacao'),
        ),
        migrations.AddField(
            model_name='avalista',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_avalista_processo', to='processos.processo'),
        ),
    ]
